### GENERAL SETTINGS ###

# Site settings
title: AGILE HUMANITIES AGENCY.
description: “Agile networks. Collaborative consultation. Open-source innovation.”
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://agilehumanities.ca"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00E496" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/Agile-Humanities-Agency-691224400932777/
  - title: twitter
    url: https://twitter.com/agilehumanities
  
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Agile Humanities Agency
    - 73 Brucewood Crescent
    - Toronto, Ontario  M6A 2G9
    - Canada
email: agile.humanities@gmail.com
tel: 416.277.5696


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Dean Irvine
    position: Director
    text: Founded the agency in 2013.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:agile.humanities@gmail.com
      - title: twitter
        url: http://twitter.com/irvined
  - name: Alan Stanley
    position: Developer
    text: Islandora and Drupal developer.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:alan.agile.humanities@gmail.com
      - title: twitter
        url: http://twitter.com/AStanley_AHA
  - name: Rosie Le Faive
    position: Developer
    text: Digital librarian, Drupal and Islandora developer, UX/UI specialist.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:rosie.agile.humanities@gmail.com
      - title: twitter
        url: http://twitter.com/rosielefaive
  - name: Bill Kennedy
    position: Designer
    text: Director of the Intelligent Machines collective.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:bill@intelligentmachines.ca
      - title: twitter
        url: http://twitter.com/stop14
    
# Clients information. Shown on Home and About pages.
clients:
  - name: Digital Humanities at Berkeley
    img: client01.png
  - name: DH Commons
    img: client02.png
  - name: The Modernism Lab at Yale
    img: client03.png
  - name: Open Modernisms
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Make it agile, by design."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Digital Humanities at Berkeley itself has contracted with Agile Humanities Agency for its branding and website design, as well for technical work associated with numerous individual research projects funded by Berkeley DH seed grants. Agile also executed the Mellon-funded work on DiRT when we recognized that there was no viable way to do it on campus. In addition to being considerably more affordable than the large, commercially oriented Drupal development companies that UC Berkeley uses for departmental websites, Agile is run by Dean Irvine, a professor who is himself a digital humanist. In addition to providing the necessary “humanities-to-techie” translation for his programmers (who have themselves worked on numerous digital humanities projects, and are more familiar with the needs and requirements of these projects than most developers), Dean is a valuable advisor on issues of project design, thanks to his own extensive background developing successful, sustainable digital humanities projects."
    author: Quinn Dombrowski
    position: Digital Humanities Specialist - berkeley.edu