### GENERAL SETTINGS ###

# Site settings
title: AGILE HUMANITIES AGENCY.
description: “Agile networks. Collaborative consultation. Open-source innovation.”
analytics: UA-77147442-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://agilehumanities.ca"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00E496" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/Agile-Humanities-Agency-691224400932777/
  - title: twitter
    url: https://twitter.com/agilehumanities
  
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Agile Humanities Agency
    - 73 Brucewood Crescent
    - Toronto, Ontario  M6A 2G9
    - Canada
email: contact@agilehumanities.ca
tel: 416.277.5696


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Dean Irvine
    position: Director
    text: Founder and director. Coordinates networks, manages partnerships, prepares quotes, negotiates contracts, consults with clients.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:admin@agilehumanities.ca
      - title: twitter
        url: http://twitter.com/irvined
  - name: Alan Stanley
    position: Developer
    text: Lead programmer. Islandora, Drupal, and WordPress developer. Works with clients to design and implement customized solutions.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:alan.agile.humanities@gmail.com
      - title: twitter
        url: http://twitter.com/AStanley_AHA
  - name: Rosie Le Faive
    position: Developer
    text: Digital librarian. Drupal and Islandora developer. Metadata and data migration. CAD modelling. Specialist in UX/UI design and accessibility. 
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:rosie.agile.humanities@gmail.com
      - title: twitter
        url: http://twitter.com/rosielefaive
  - name: Bill Kennedy
    position: Designer
    text: Member of the Intelligent Machines collective. Graphic design, UX, information architecture, project management, eCommerce and eBooks, mobile apps.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:bill@intelligentmachines.ca
      - title: twitter
        url: http://twitter.com/stop14
  - name: David John Evans
    position: Developer
    text: Programmer. Islandora and Drupal developer.
    img: team05.jpg
    social:
      - title: envelope #use for email address
        url: mailto:david@djevans.info
      - title: twitter
        url: https://twitter.com/davidjohnevans
  - name: Dana Wheeles
    position: Project manager
    text: Project management, content curation, information architecture, UX/UI design, metadata.
    img: team06.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dana@danawheeles.com
      - title: twitter
        url: https://twitter.com/bluesaepe      
  - name: Wolf Maul
    position: Developer
    text: Owner of Semandra, Inc. Drupal, Islandora, Joomla, and WordPress. UX/UI, graphic design, theming, SEO, interactive data visualizations, semantic web/open data, mobile apps.
    img: team07.jpg
    social:
      - title: envelope #use for email address
        url: mailto:wolf@semandra.com
      - title: twitter
        url: https://twitter.com/wolfularity
  - name: Milena Radzikowska
    position: Interaction designer
    text: Text visualization, manufacturing decision support, interaction design, experimental interface design, prototyping.
    img: team08.jpg
    social:
      - title: envelope #use for email address
        url: mailto:mradzikowska@gmail.com
      - title: twitter
        url: https://twitter.com/CanDesignLove     
# Clients information. Shown on Home and About pages.
clients:
  - name: Digital Humanities at Berkeley
    img: client01.png
  - name: Yale University
    img: client02.png
  - name: University of Virginia
    img: client03.png
  - name: University of California at Berkeley
    img: client04.png
  - name: University of Victoria
    img: client05.png
  - name: York University
    img: client06.png
  - name: Northeastern University
    img: client07.png
  - name: Vancouver Island University
    img: client08.png  
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Agile networks. Collaborative consultation. Open-source innovation. Make it agile, by design."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Digital Humanities at Berkeley has contracted with Agile Humanities Agency for its branding and website design, as well for technical work associated with numerous individual research projects funded by Berkeley DH seed grants. Agile also executed the Mellon-funded work on DiRT when we recognized that there was no viable way to do it on campus. In addition to being considerably more affordable than the large, commercially oriented Drupal development companies that UC Berkeley uses for departmental websites, Agile is run by Dean Irvine, a professor who is himself a digital humanist. In addition to providing the necessary “humanities-to-techie” translation for his programmers (who have themselves worked on numerous digital humanities projects, and are more familiar with the needs and requirements of these projects than most developers), Dean is a valuable advisor on issues of project design, thanks to his own extensive background developing successful, sustainable digital humanities projects."
    author: Quinn Dombrowski
    position: Digital Humanities Specialist – berkeley.edu